apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: service-managednamespace-template
  description: Backstage template for creating Kubernetes namespaces with automated RBAC configuration
  annotations:
    github.com/project-slug: open-service-portal/service-managednamespace-template
spec:
  type: url
  targets:
    - ./template.yaml
