apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: managed-namespace
  title: Managed Namespace with RBAC
  description: |
    Create a Kubernetes namespace with automated RBAC configuration for owners, maintainers, and readers.

    ⚠️ **GitHub Authentication Required**
    This template creates a Pull Request using YOUR GitHub account.
    Please ensure you are signed in with GitHub before proceeding.

    📋 To check: Click your profile icon → Settings → Authentication Providers
  annotations:
    backstage.io/managed-by-location: url:https://github.com/open-service-portal/service-managednamespace-template/blob/main/template.yaml
    backstage.io/source-location: url:https://github.com/open-service-portal/service-managednamespace-template/tree/main/
  tags:
    - kubernetes
    - namespace
    - rbac
    - infrastructure
    - crossplane
    - recommended
spec:
  owner: group:platform-team
  type: infrastructure

  parameters:
    - title: Namespace Configuration
      required:
        - name
        - owners
      properties:
        name:
          title: Namespace Name
          type: string
          description: Name of the Kubernetes namespace to create (cannot be changed after creation)
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          maxLength: 63
          ui:autofocus: true
          ui:help: 'Lowercase alphanumeric characters and hyphens only, must start and end with alphanumeric'

        owners:
          title: Owners
          type: array
          description: At least 2 owners required. Owners have full control including namespace deletion.
          minItems: 2
          items:
            type: string
            ui:field: EntraIdEntityPicker
          ui:options:
            addable: true
            orderable: false
            removable: true

        maintainers:
          title: Maintainers (Optional)
          type: array
          description: Maintainers can create, edit, and delete resources within the namespace
          items:
            type: string
            ui:field: EntraIdEntityPicker
          ui:options:
            addable: true
            orderable: false
            removable: true

        readers:
          title: Readers (Optional)
          type: array
          description: Readers have read-only access to all resources within the namespace
          items:
            type: string
            ui:field: EntraIdEntityPicker
          ui:options:
            addable: true
            orderable: false
            removable: true

    - title: Repository Configuration
      required:
        - repoUrl
        - targetPath
      properties:
        repoUrl:
          title: Target Repository
          type: string
          description: Select the GitHub repository where the ManagedNamespace XR will be stored
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - open-service-portal
            # Show user's accessible repos
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN

        targetPath:
          title: Target Path
          type: string
          description: Path within the repository where the XR should be created
          default: system/ManagedNamespace
          ui:help: 'Default follows cluster-scoped layout: system/ManagedNamespace'

        createPullRequest:
          title: Create Pull Request
          type: boolean
          description: Create a pull request instead of committing directly to main branch
          default: true
          ui:widget: radio
          ui:options:
            - title: Create PR (recommended)
              value: true
            - title: Direct commit to main
              value: false

  steps:
    # Step 1: Validate GitHub authentication
    - id: validate-github-auth
      name: Verify GitHub Connection
      action: portal:validate:github-auth
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        userEmail: ${{ user.entity.spec.profile.email }}
        userName: ${{ user.entity.spec.profile.displayName }}

    # Step 2: Generate unique XR name
    - id: generate-xr-name
      name: Generate XR Name
      action: portal:utils:generateId
      input:
        length: 8
        type: hex

    # Step 3: Create ManagedNamespace XR manifest
    - id: fetch-template
      name: Generate ManagedNamespace XR
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          xrName: ${{ parameters.name }}-${{ steps['generate-xr-name'].output.id }}
          owners: ${{ parameters.owners }}
          maintainers: ${{ parameters.maintainers | default([]) }}
          readers: ${{ parameters.readers | default([]) }}
          targetPath: ${{ parameters.targetPath }}

    # Step 4: Publish to GitHub (PR or direct commit)
    - id: publish
      name: Publish to GitHub
      action: publish:github:pull-request
      if: ${{ parameters.createPullRequest }}
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: 'feat: add ManagedNamespace ${{ parameters.name }}'
        branchName: managed-namespace-${{ parameters.name }}
        description: |
          ## ManagedNamespace: ${{ parameters.name }}

          **XR Name:** `${{ parameters.name }}-${{ steps['generate-xr-name'].output.id }}`

          **Created by:** @${{ user.entity.spec.profile.displayName || user.entity.metadata.name }} (${{ user.entity.spec.profile.email }})

          ### RBAC Configuration

          **Owners:**
          ${{ parameters.owners | dump(2) }}

          **Maintainers:**
          ${{ parameters.maintainers | dump(2) | default('None') }}

          **Readers:**
          ${{ parameters.readers | dump(2) | default('None') }}

          ---

          🤖 Generated with Backstage
        targetPath: ${{ parameters.targetPath }}

    - id: publish-direct
      name: Publish Directly to Main
      action: publish:github
      if: ${{ not parameters.createPullRequest }}
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        gitCommitMessage: 'feat: add ManagedNamespace ${{ parameters.name }}'
        targetPath: ${{ parameters.targetPath }}

  output:
    links:
      - title: ${{ parameters.createPullRequest && 'View Pull Request' || 'View Repository' }}
        url: ${{ parameters.createPullRequest && steps.publish.output.remoteUrl || steps['publish-direct'].output.remoteUrl }}